name: "SENATOROV"

permissions:
  contents: write  # Grant write access to the repository contents
on:
  push:
    branches:
      - "**"
  pull_request:
    branches:
      - "**"
  schedule:
    - cron: "0 0 * * *" # Run every day
  workflow_dispatch:
  create:
  delete:
  release:
  issues:
  pull_request_review:
  pull_request_review_comment:

jobs:
  black:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
        allow-prereleases: true
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install black "black[jupyter]" nbqa
    - name: Black
      run: |
        black --diff --line-length=79 $(git ls-files '*.py' '*.ipynb')
        nbqa black --fiff --line-length=79 $(git ls-files '*.py' '*.ipynb')
    - name: commit  
      run: |
        git config --local user.name "github-actions"
        git config --local user.email "actions@github.com"
        git add .
        git commit -m "ВНИМАНИЕ! КОД ОТФОРМАТИРОВАН ПО PEP8 / SENATOROV" || echo "No changes to commit"
        git push origin main --force
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}


     
