name: "SENATOROV"

permissions:
  contents: write  # Grant write access to the repository contents
on:
  push:
    branches:
      - "**"
  pull_request:
    branches:
      - "**"
  schedule:
    - cron: "0 0 * * *" # Run every day
  workflow_dispatch:
  create:
  delete:
  release:
  issues:
  pull_request_review:
  pull_request_review_comment:

jobs:
  black:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
        allow-prereleases: true
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install black "black[jupyter]" nbqa
    - name: Black
      run: |
        black --diff --line-length=79 $(git ls-files '*.py' '*.ipynb')
        nbqa black --diff --line-length=79 $(git ls-files '*.py' '*.ipynb')
        
    - name: Commit and push changes
      env:
        GH_TOKEN: ${{ secrets.GH_TOKEN }}
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        git remote set-url origin https://x-access-token:${{ secrets.GH_TOKEN }}@github.com/${{ github.repository }}
        git pull
        git add .
        git diff --quiet || (git commit -m "Convert notebooks to Python scripts" && git push)




     
