name: pyright
on:
  push:
    branches:
      - "**"
  schedule:
    - cron: "0 0 * * *" # Run every day
  workflow_dispatch:
  create:
  delete:
  release:
  issues:
  pull_request:
    branches:
      - "**"
jobs:
  ruff:
    runs-on: ubuntu-latest
    steps:
    
    - uses: jakebailey/pyright-action@v1
      with:
        pylance-version: latest-release
