name: pyright

on:
  push:
    branches:
      - "**"
  schedule:
    - cron: "0 0 * * *" # Run every day
  workflow_dispatch:
  create:
  delete:
  release:
  issues:
  pull_request:
    branches:
      - "**"

jobs:
  pyright-check:
    runs-on: ubuntu-latest
    steps:
      # Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v2

      # Install Python and nbqa
      - name: Set up Python environment
        run: |
          pip install nbqa pyright

      # Run Pyright via nbqa
      - name: Run Pyright
        run: nbqa pyright .
