# https://beta.ruff.rs
name: ruff
on:
  push:
    branches:
      - "**"
  schedule:
    - cron: "0 0 * * *" # Run every day
  workflow_dispatch:
  create:
  delete:
  release:
  issues:
  pull_request:
    branches:
      - "**"
jobs:
  ruff:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: pip install --user ruff
      - run: ruff check --output-format=github .
